version: '3.8'
services:
    
    front-end:
      container_name: Angular
      build:
        context: .
      ports:
        - "5000:5000"
      networks:
        - quickx
      
    back-end:
      container_name: MongoDB
      build:
        context: .
      environment:
        MONGO_URI: ${MONGO_URI}
      networks:
        - quickx
      healthcheck:
        test: ["CMD-SHELL", "curl -f $${MONGO_URI} || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 5

networks:
  quickx:
    name: quickx
